### ISSUE TITLE
Skewed view of scene in viewer

### ISSUE THREAD

**Issue by jakobs** [rock-simulation/mars#12]
When I start mars, I get a skewed view of the scene:

![screenshot from 2014-11-30 21 00 23](https://cloud.githubusercontent.com/assets/160834/5239100/2f556b5a-78d4-11e4-87b3-8455354b2df7.png)

when I move the window, it goes back to normal

![screenshot from 2014-11-30 21 00 36](https://cloud.githubusercontent.com/assets/160834/5239103/5023c46c-78d4-11e4-8b4c-2d674410bfe6.png)

changing the size of the window btw. does not fix the issue. Only moving the window.

I am using 
01:00.0 VGA compatible controller: NVIDIA Corporation GF104 [GeForce GTX 460] (rev a1)
Driver Version: 331.38

**Comment by jakobs** [comment]
Occurs on both Ubuntu 14.04 with Unity and Mint 17 with cinnamon.

**Comment by malter** [comment]
fixed (second try)

**Comment by jakobs** [comment]
cool! fixed for me.
