### ISSUE TITLE
Removing Dependancy to mars/cmake

### ISSUE THREAD

**Issue by goldhoorn** [rock-simulation/mars#20]
since mars is using the rock-base types, the rock-cmake is already required.

In the long run should be the mars-cmake-makros merged with the rock-cmake-macros.
By doing so each mars-library could be build independent of mars(/cmake).
and we removing the duplication of code...

**Comment by malter** [comment]
The installation of the mars.cmake is now moved to the lib_manager (lib_manager.cmake). The lib_manager also installs the cmake extenison and there is no package dependency to mars/cmake any more. Howerver, it would be cool tho merge the lib_manager.cmake functions to the rock-cmake-macros.
