### ISSUE TITLE
segfault when loading pool.scn

### ISSUE THREAD

**Issue by jakobs** [rock-simulation/mars#24]
When I try to load the pool.scn
https://github.com/auv-avalon/avalon_simulation/blob/master/configuration/pool.scn
I get a segfault.

**Comment by goldhoorn** [comment]
Did you already try unset LANG sometimes we had problems with this even we tried to fix this inside mars? (Only a idea before i had the time to test on my own)

**Comment by goldhoorn** [comment]
*confirmed*

bt:
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff5618838 in main_arena () from /lib/x86_64-linux-gnu/libc.so.6
(gdb) bt
#0  0x00007ffff5618838 in main_arena () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007fffec652e5d in osg::StateSet::setAttributeAndModes(osg::StateAttribute*, unsigned int) () from /usr/lib/x86_64-linux-gnu/libosg.so.100
#2  0x00007fffee71451b in mars::graphics::DrawObject::updateShader (
    this=0xb68ec0, lightList=std::vector of length 1, capacity 1 = {...}, 
    reload=<optimized out>, shaderSources=...)
    at /home/goldhoorn/bootstraps/mars/simulation/mars/graphics/src/3d_objects/DrawObject.cpp:585
#3  0x00007fffee7187aa in mars::graphics::DrawObject::setUseFog (
    this=0xbd0d60, val=<optimized out>)
    at /home/goldhoorn/bootstraps/mars/simulation/mars/graphics/src/3d_objects/DrawObject.cpp:687
#4  0x00007fffee6d0be0 in mars::graphics::GraphicsManager::setGraphicOptions (
    this=0x7745f0, options=...)
    at /home/goldhoorn/bootstraps/mars/simulation/mars/graphics/src/GraphicsManager.cpp:477
#5  0x00007fffd65e174a in mars::scene_loader::Load::loadGraphic (
    this=<optimized out>, config=...)
    at /home/goldhoorn/bootstraps/mars/simulation/mars/scene_loader/src/Load.cpp:374
#6  0x00007fffd65ddfda in mars::scene_loader::Load::loadScene (
    this=0x7fffffffc700)

**Comment by jakobs** [comment]
I have a fix on my machine at home. Will commit this evening.

**Comment by malter** [comment]
should be fixed?

**Comment by jakobs** [comment]
Yes, thanks.
