### ISSUE TITLE
Basic Plugin Tutorial

### ISSUE THREAD

**Issue by mmeder** [rock-simulation/mars#29]
> Now copy the "mars_default" configuration to "mars_basic_plugin" and add the plugin to the "other_libs.txt" within "mars_basic_plugin" to load the new plugin when starting MARS.

There is no file called "other_libs.txt" but a file called "other_libs.txt.example". This should be adjusted either in the tutorial or by changing the filename.

> Currently the plugin does not do anything, but it should show up in the list of loaded plugins which you can find under the menu entry: File->Library Info...

The Library isn't automatically loaded as stated in the tutorial. But it is possible to load it via the created .so file.

> You should also have a robot scene file to start with (if not you can use this scene <robo.scn>_ to follow the tutorial.

No "robo.scn" file found. So Tutorial example doesn't work for me.

> The script will ask you for the project name, from which it will also try to derive the class name of the main c++ class...

Entering accidently a " into the project description did damage the resulting CMakeLists.txt and thuss the following scripts.

**Comment by kavonszadkowski** [comment]
Thanks for the input. We changed the entire configuration setup last week and haven't adapted the docs, yet. I'll see to it.

**Comment by kavonszadkowski** [comment]
Solved all points except for the example scene file. This should probably be updated to a SMURF file which we first have to create. However, loading a scene/SMURF file is not essential to creating and using a plugin, so I'll close this for now.
