### ISSUE TITLE
LibManager Can't Load mars_graphics and log_console

### ISSUE THREAD

**Issue by Rauldg** [rock-simulation/mars#34]
Hello,

In a rock installation I get the following messages when running `mars_app`:
```
Loading default core libraries...
LibManager: could not find "mars_graphics"
LibManager: could not find "log_console"
```

Under `install/lib` I have the following libraries that look related:
```
libmars_graphics.so
libdatalogger.so
libpocolog_cpp.so
```

Thanks for the help

**Comment by malter** [comment]
It's not an error. The simulation library is loaded before mars_graphics but later on checks the dependency again. If the 3d graphics window pops up everything is loaded fine.
I think the log_console isn't build in the rock installation and it's not a necessary component. Logging will be done in the terminal without log_console.

**Comment by Rauldg** [comment]
OK, thanks. I'll close the issue.
