### ISSUE TITLE
LibManager never unloads a library

### ISSUE THREAD

**Issue by arneboe** [rock-simulation/mars#5]
According to the comments in the code `LibManager::unloadLibrary()` should not be called directly.
`releaseLibrary()` should be used insted.

`releaseLibrary()` contains the following code:

        if(theLib->useCount <= 0 && theLib->wasUnloaded) {
          unloadLibrary(libName);
       }

I.e. a library will be unloaded, if it is no longer used and `theLib->wasUnloaded` has been set to true.
However `theLib->wasUnloaded` is only set in `unloadLibrary()`.
Thus a library is only unloaded, if `unloadLibrary()` is called directly, which is forbidden.

**Comment by malter** [comment]
Closed because `unloadLibrary(libName);` works fine. The documentation just says: use it only if you know what you are doing. For the general MARS case only releaseLibrary is used/needed.
