### ISSUE TITLE
Bug in anchoring

### ISSUE THREAD

**Issue by maotto** [rock-simulation/mars#57]
All object behave like they were anchored in the world, disregarding the entry in the smurfs file.

In 4f395f57a114ddd57f9b4d3ef0437679c82f1ba7, it still works, i.e., anchoring "none" allows objects to fall.

the anchor settings have been adjusted in b31126bb8064ceda26e8c4debac9c50b9f2dd384 so maybe the problem was caused there.

Maybe @kavonszadkowski can help.

**Comment by malter** [comment]
By not defining the anchor in the smurfs file or comment the anchor line the objects should behave correctly. Just added the "anchor: none" option to the current develop branch.
