### ISSUE TITLE
#error You can only #define dSINGLE or dDOUBLE, not both.

### ISSUE THREAD

**Issue by HWiese1980** [rock-simulation/mars#72]
Hello everyone,

while bootstrapping BOLeRo I'm getting this error when it tries to build `simulation/mars/sim`. 

`simulation/ode` defines `dSINGLE` in its `configure`, `simulation/mars-sim` defines `dDOUBLE` in its `CMakeLists.txt`. `make` of `simulation/mars/sim` fails with the above mentioned error message. 

What causes this error? Is `ode` wrong or `mars/sim`?

Thanks

**Comment by malter** [comment]
Hey,

ode should be configured with double precision. It should be an argument for the configure script like --enable-double-precision which should be done by pybob.

Can you give some more information about your system configuration and how you performed the bootstrap?

**Comment by HWiese1980** [comment]
Sure. My system is a Ubuntu 16.04 x64. I performed the bootstrap by means of the original `bootstrap_bolero.sh` from GitLab, but with one alteration from the normal process: I enabled the `mars_environment` in `autoproj/manifest`.

**Comment by malter** [comment]
Ok, i did the following:

1. bash bootstrap_bolero.sh
2. cd bolero-dev
3. source env.sh
4. uncomment mars_environment in autoproj/manifest
5. bob-bootstrap

This way on my ubuntu everything builds fine. Can you try that again in exactly that way? And also wait for bootstrap_bolero.sh to finish until changing the manifest.

**Comment by HWiese1980** [comment]
Okay, I've removed my `bolero-dev` folder, downloaded the `bootstrap_bolero.sh` from the original BOLeRo repository again and followed your steps precisely. I'm still getting the error. By the way, to avoid a misconception: I did not interrupt the bootstrap process beforehand. I've waited for it to finish every time.

**Comment by malter** [comment]
Ok, if you did it the same way as me it must be due to your system configuration. I have a virtual box with ubuntu 16.04 x64 all updates installed.

Maybe you have an ode version installed via apt-get?

**Comment by malter** [comment]
If that was the problem, I just updated pybob and it should work now.

**Comment by HWiese1980** [comment]
Looks like that has indeed been the reason. Your pybob update appears to have fixed the issue. I'll try it once more to verify it and will close the issue if it works.

**Comment by HWiese1980** [comment]
Okay, confirmed working again. Thanks a lot!
