### ISSUE TITLE
different orientation of '.stl' meshes when importing '.scn' or '.urdf' files?

### ISSUE THREAD

**Issue by bergatt** [rock-simulation/mars#8]
I have a problem while importing `.stl` files. When loading an `.urdf` file using `.stl` files I have to add an additional rotation of *-90°* around the x-axis (see line *280* of [gui_helper_functions.cpp](https://github.com/rock-simulation/mars/blob/master/graphics/src/gui_helper_functions.cpp) ). But when I save the imported scene as an `.scn` file and try to load the scene again it somehow "overshoots" (the objects are rotated *90°* "too far").
It seems to me, that in order to fix this you have to know when calling `GuiHelper::getPhysicsFromOBJ()`, if you are currently importing a `.scn`or `.urdf`file. Any ideas? Is there a way to determine that from the mesh which is currently loaded?

@malter

**Comment by malter** [comment]
What is the current state here? Can we close this issue or is there still a problem with the stl import/export?

**Comment by bergatt** [comment]
Had not had the time to have a further look. Will set it on my ToDo list! I'll come back to you, if I have any news!

**Comment by malter** [comment]
Close this issue due to no further feedback whether there are still problems with stl files.
